### ISSUE TITLE
Intellisense window does not show after typing '-' if it has some text right after the typed '-'

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#103]
For eg:
Original:
Write-Host
Edit:
Remove '-' and retype '-'

Expected: intellisense window shown
Actual: looks like intellisense triggers, however no intellisense window shown

**Comment by ASayre** [comment]
@EricMSFT  I'm not reproing this currently.  It is possible I'm missing something?

**Comment by HuanhuanSunMSFT** [comment]
Cannot repro. Close this.
