### ISSUE TITLE
Long running tasks block the REPL Window

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#106]
Long running tasks block the REPL Window

Pipeline not executed because a pipeline is already executing. Pipelines cannot be executed concurrently.

In REPL:

``` powershell
$RemoteAppLog = New-Object -TypeName System.Diagnostics.EventLog Application,192.168.1.81
$RemoteAppLog
Write-Host "Hi"
```

**Comment by ASayre** [comment]
TODO: Figure out the proper experience for this situation

**Comment by adamdriscoll** [comment]
ISE prevents you from entering or running another command.

**Comment by ericdevg** [comment]
Looks like this issue was fixed by some previous change. Close it till someone starts seeing it again.
