### ISSUE TITLE
Auto-Indentation is lost upon new lines

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#108]
We lose  auto indentation each time we hit 'enter'

Example:

[tab][tab]"Text"[Enter]
becomes
[tab]
pressing [enter] again removes that last tab.

The behavior is somewhat random.  Example, if we hit five tabs, and enter, we go down to one tab of indentation.

**Comment by ASayre** [comment]
adamdriscoll/poshtools/112

**Comment by ASayre** [comment]
This was related to an issue that was previously reported and had prior investigation.  Did you want to take a look, @adamdriscoll

**Comment by adamdriscoll** [comment]
Sure. There is a SmartIndenter class that is likely the culprit.

**Comment by ASayre** [comment]
Also fixed in #373
