### ISSUE TITLE
Moving code snippet with the word configuration fast by keep pressing enter/backspace will cause an extension exception

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#109]
![image](https://cloud.githubusercontent.com/assets/10081208/6071574/34bd359e-ad4c-11e4-933a-479bb6e3044c.png)

The exception message in ActiveLog.xml:

  <entry>
    <record>721</record>
    <time>2015/02/05 23:28:22.022</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: span&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)&#x000D;&#x000A;   at PowerShellTools.Classification.PowerShellOutliningTagger.&lt;GetTags&gt;b__0(TagInformation`1 current)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()&#x000D;&#x000A;   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)&#x000D;&#x000A;   at PowerShellTools.Classification.PowerShellOutliningTagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>

**Comment by ASayre** [comment]
@bmoore-msft Was running into this too.  Potentially more often now.

**Comment by ASayre** [comment]
@ChrisLynchHP was running into this now too.

**Comment by HuanhuanSunMSFT** [comment]
This should have been covered in the fix for colorization race condition
