### ISSUE TITLE
Reformat Script deletes everything

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/poshtools#114]
Windows 8.1

Repro:
1. Start VS and create PowerShell script project
2. Right click in the editor and select 'Reformat Script'

Expected:
It should reformat the script or at least do nothing

Actual:
It deletes all contents of the script

**Comment by ASayre** [comment]
Related to https://github.com/adamdriscoll/poshtools/issues/42- In the meantime, we should disable the command so we don't break anyone.

**Comment by adamdriscoll** [comment]
Agreed. It's not a complete reformatter anyways.

**Comment by ASayre** [comment]
Fixed with #134 [ie, command disabled]
