### ISSUE TITLE
PowerShell Module Project test.ps1 file has errors when run

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/poshtools#115]
Windows 8.1

Repro:
1. Open VS and create a new PowerShell Module project
2. Run Module.test.ps1

Output:
[ERROR] Describe : The term 'Describe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
[ERROR] At C:\users\erijiz\documents\visual studio 2013\Projects\PowerShell Module Project2\PowerShell Module Project2\Module.test.ps1:1 char:1
[ERROR] is correct and try again.
[ERROR] + Describe "Get-Function" {
[ERROR] + ~~~~~~~~
[ERROR]     + CategoryInfo          : ObjectNotFound: (Describe:String) [], CommandNotFoundException
[ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
[ERROR]

**Comment by ASayre** [comment]
@adamdriscoll : What's intended behavior here of F5 of the module project?  It seems to be trying to execute the tests

**Comment by adamdriscoll** [comment]
It should attempt to run whatever script is open. I'm surprised it's just running the tests. If you don't have Pester installed, you will get the error above.

**Comment by ASayre** [comment]
we have the comment in there to go get Pester, as this is arbitrary PowerShell
