### ISSUE TITLE
Unable to Switch-AzureMode in the doc window

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#133]
The Switch-AzureMode cmdlet switches the azure modules that are loaded (Resource Manager vs. Service Mgmt) - this changes the available set of cmdlets.  It also affects intellisense in the editor.

In the ISE when you switch modes in the REPL window, the editor also switches.  That doesn't seem to work in poshtools so I can't find a way to get intellisense for AzureRM cmdelts.

**Comment by ericdevg** [comment]
This has been fixed by d05c08f. please go ahead to verify.

**Comment by ASayre** [comment]
@bmoore-msft Ping re you getting a chance to verify?
