### ISSUE TITLE
Intellisense completion will remove starting bracket

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#138]
Have a folder C:\Test

``` powershell
MyFunction("C:\Tes");
```

Have cursor right after 'tes'  Hit ctrl-Space to trigger intellisense.  Hit down and enter to select and trigger intellisense completion.

It replaces it with:

``` powershell
MyFunction"C:\Test"");
```

**Comment by HuanhuanSunMSFT** [comment]
It's an issue of Intellisense, not relevant to brace matching. Wherever Intellisense is triggered for path, it will delete the character just in front of it and add another double quote. This annoying bug will be my next target :8ball:
