### ISSUE TITLE
Debugger freezes inside a Terminating Exception

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#153]
F5'ing through this script.

Seems to be related to just the `Start-DscConfiguration -Path .\FileResourceDemo -Wait -Force` line.

![image](https://cloud.githubusercontent.com/assets/10080679/6260877/904d7a38-b79a-11e4-9c7e-2d0562e04043.png)

**Comment by ericdevg** [comment]
@AndreSayreMSFT  Did you try with latest dev build? I cannot repro this issue on latest dev build.
