### ISSUE TITLE
Product Name is incorrect, file version should be auto-incremented for B2B upgrade

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#163]
![capture](https://cloud.githubusercontent.com/assets/10081101/6360097/5cc713fe-bc2c-11e4-95bd-d08818e04416.PNG)

**Comment by ASayre** [comment]
ProductName has been corrected, FileVersion for B2B upgrade still needs to be done, as the VSIX build number needs to be auto incremented as well.
