### ISSUE TITLE
consider adding blank line to REPL prompt

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#165]
In ISE, after typing a command, even one that does not give a response to the host, there is a separation in the lines - this is much more readable than single spaced prompts

**Comment by ASayre** [comment]
Not always, but we should match the experience:

```
PS C:\Users\AndreSay> Write-Host "Hi"
Hi

PS C:\Users\AndreSay> Write-Host "Hi" -NoNewline
Hi
PS C:\Users\AndreSay> 
```
