### ISSUE TITLE
ADAL & Credential Windows have sometimes appear behind Visual Studio

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#174]
Try Add-AzureAccount or Get-Credential; sometimes the auth dialog appears behind Visual Studio, with no obvious prompt.

**Comment by ASayre** [comment]
Related to #214 ?

**Comment by ASayre** [comment]
@cawams had Interest in this; please holler if this is blocking anything.

**Comment by ericdevg** [comment]
Should be fixed via commit 391c1fa
@cawams would you mind to give our latest build a try, reopen if you are still seeing the issue.

**Comment by ASayre** [comment]
@EricMSFT This still repos on the ADAL dialog; reopening
