### ISSUE TITLE
Need to click F10 twice to step over certain statement

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#181]
``` powershell
$b=[char]0x263a
$c=[byte]('0x' + 'FF')
$d=[long]1
$e=$true
$f = 1.2
$g = [single]1.2
$h = [double]1.2

$myArray = @(1,"Hello",3.5,"World")
```

since the start, keep pressing F10 to step over till you hit last statmente: $myArray=@(1, "Hello", 3.5, "World")

You need to press f10 for twice in order to step over this statement

**Comment by ASayre** [comment]
Moved to match #303

**Comment by ericdevg** [comment]
I just realized that ISE gives the same experience, you take two F10 to get over this statement. The only improvement we can do is highlight the execution part, which will help user to understand this statement was actually broke down to two statement in execution. which should be tracked by #303
