### ISSUE TITLE
Need to wait for the current PowerShell host execution item to complete...

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#182]
...before executing the next action

Can/Will get Pipeline errors in REPL window for example, if we should otherwise be waiting on PS execution from our commands.

**Comment by ericdevg** [comment]
We do get the error from pipeline if you try to execute simultaneously, however I think we should wait for the first one to finish, so that user does not run into the error all the time, consider we are indeed not able to run simultaneously. I think this is pointing to the same thing as #106

**Comment by ASayre** [comment]
Certainly related, but with multiple entry points for feeding stuff to the runSpace.
