### ISSUE TITLE
Remote process crash when executing a script on remote machine

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#197]
Connected to a remote computer
F5 and right click, execute as script both repro this 100%.

![image](https://cloud.githubusercontent.com/assets/10080679/6422012/f3f0609c-be88-11e4-99e2-cbd78e3b038f.png)

After continuing to run, PowerShell runspace state changes to: 'Broken'

**Comment by ericdevg** [comment]
That is good found, so looks like you are trying to execute/debug local script after you entered remote session. According to powershell ISE, it prevents people to execute anything on local after entered into remote session. We should probably do the same.

**Comment by ASayre** [comment]
We should provide a mechanism to Execute a script on a remote session/machine then; Potentially Soln explorer Context menu.  Maybe Editor context menu too? @bmoore-msft

**Comment by ericdevg** [comment]
NOTE:
1. Editor context menu is the way we currently supported for debugging remote file, and that is also the only way of doing that as far as I know.
2. By opening remote file, there is only an empty solution created.
