### ISSUE TITLE
Default project names shouldn't have spaces in them

### ISSUE THREAD

**Issue by huguesv** [microsoft/poshtools#202]
Right now the suggested project names have spaces in them like this:
`PowerShell Module Project1`
`PowerShell Script Project1`

I would suggest to use this instead:
`PowerShellModule1`
`PowerShellScript1`

This is controlled in the .vstemplate file, like this:

```
    <DefaultName>PowerShellModule</DefaultName>
    <ProvideDefaultName>true</ProvideDefaultName>
```

**Comment by ASayre** [comment]
Thanks!  We'll get this fixed.
