### ISSUE TITLE
Capitalization of menu items

### ISSUE THREAD

**Issue by huguesv** [microsoft/poshtools#204]
Standard for menu items in VS is to capitalize:

Execute as script => Execute as Script
Execute selection => Execute Selection

**Comment by ASayre** [comment]
Thanks!  We'll get this fixed.

**Comment by ASayre** [comment]
Assigning this to Jing to fix, related to some other string changes [ #90 ] :)

**Comment by jinglouMSFT** [comment]
Thanks Andre for code review, Hugues for logging the issue.
