### ISSUE TITLE
Intellisense is broken when using backspace

### ISSUE THREAD

**Issue by dgrala** [microsoft/poshtools#205]
If I type "Start" it gives me correct suggestions, but then if I use backspace to erase it, the suggestions window stays. When I type say "Import" it still shows completion for "Start".

**Comment by dgrala** [comment]
![ps](https://cloud.githubusercontent.com/assets/10715890/6424193/ac47b7c0-bea8-11e4-9f40-458228f05f74.png)

**Comment by ASayre** [comment]
Thanks for reporting this, and adding the steps!  For tracking: related to issues described in #9
