### ISSUE TITLE
need support for dark theme

### ISSUE THREAD

**Issue by lucamorelli** [microsoft/poshtools#207]
I installed the tool with vs 2015 with dark theme, and the ide, even working with .cs files, shows inverted colors in the editor and in the scrollbar on the right.
I suppose that is changing the editor settings even for C# files

**Comment by ASayre** [comment]
Thanks for reporting this!  This looks to be related to #111

**Comment by ASayre** [comment]
@lucamorelli Our _initial_ investigation is that there may be a bug in VS2015 causing this!  We're looking into it and trying to track this down.

**Comment by lucamorelli** [comment]
ok, thanks for the info

**Comment by gwojan** [comment]
In VS2013, the code map/scrollbar loses the dark theme and has a white background.

**Comment by ASayre** [comment]
@gwojan @lucamorelli Do the latest nightly dev builds patch things up for you? https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts

**Comment by lucamorelli** [comment]
just installed, seems to works. thanks!

**Comment by gwojan** [comment]
Ack! :frowning: I uninstalled the previous version but now receive **`This extension is already installed to all applicable products.`** when trying to install the latest build in VS2013.
