### ISSUE TITLE
Watch window doesn't show object properties

### ISSUE THREAD

**Issue by jpsnover** [microsoft/poshtools#208]
foreach ($p in Get-Process *ss)
{
    $n = $p.name
    $i =$p.id
    Write-Host "name = $n  id = $i"
}

I put n,I, & p in the watch window.  The p var shows the > but when I click on it I don't see the properties.

I think the problem is that it is showing the TYPE of p as "System.Management.Automation.PSObject" which means that it is looking at the PS wrapper object instead of using the wrapper to view the PS adapted view of the object.  If that doesn't make any sense, give me a call and I can drop by to illustrate the issues.

Jeffrey Snover[MSFT]

**Comment by ASayre** [comment]
Thanks for reporting this, Jeffrey.  Glad to have you dogfooding & taking a look at the product!  The issue makes sense, and we'll get that fixed up!

I'll still ping you tomorrow to see if there's other issues!
