### ISSUE TITLE
Null reference while examining the properties through reflection

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#215]
While enumerating each properties of object through reflection, need check null before adding it into variable list.

**Comment by ASayre** [comment]
[As part of it and per convo, it'd be good to flatten out the inner exception in that message, so we don't potentially hide any other unknown errors]

**Comment by ericdevg** [comment]
"[As part of it and per convo, it'd be good to flatten out the inner exception in that message, so we don't potentially hide any other unknown errors]" is going to be taken cared by next merge request.
