### ISSUE TITLE
Typing two intellisense triggering character fast will cause completion list not showing up

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#237]
Type in a normal speed:
Write-Host "C:\
Expected: It should show the completion list. 
Actual: No completion list shows though status bar indicates it seems having triggered IntelliSense

**Comment by ASayre** [comment]
Potential same root cause as #109?

**Comment by HuanhuanSunMSFT** [comment]
This one should have been covered in racing condition fix. @AndreSayreMSFT @EricMSFT

**Comment by ASayre** [comment]
Agreed.  Closing this out.
