### ISSUE TITLE
[Intellisense] OutOfRangeException when double click to open script file with WF defined

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#245]
![capture](https://cloud.githubusercontent.com/assets/10081101/6676514/99827e28-cbe5-11e4-8d6a-c2dd360327c9.PNG)

REPRO: open script file with below content in your powershell project:

``` powershell
workflow Verb-Noun 
{
    Param
    (
        # Param1 help description
        [string]
        $Param1,

        # Param2 help description
        [int]
        $Param2
    )

    {
        Write-Host "Hello"
    }
}

Verb-Noun -Param1 "Hi" -Param2 42
```

**Comment by ASayre** [comment]
@HuanhuanSunMSFT Looks to be related to the fix with pull request https://github.com/Microsoft/poshtools/pull/241
