### ISSUE TITLE
Breakpoint was bound for twice

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#253]
![capture](https://cloud.githubusercontent.com/assets/10081101/6699798/ac159218-ccc2-11e4-8bbe-a5ae5e9d02e4.PNG)

So ends up duplicate entries in breakpoint window.

**Comment by ASayre** [comment]
Is this root cause of #181, or a separate issue?

**Comment by ericdevg** [comment]
Unfortunately, does not seem to be related.
