### ISSUE TITLE
Expand description in the VSIX Manifest

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#255]
We should have a better description here:

![image](https://cloud.githubusercontent.com/assets/10080679/6719959/f3a2f9a4-cd7b-11e4-8021-4565e4b207be.png)

**Comment by ASayre** [comment]
`Run, edit, and debug PowerShell scripts and cmdlets from within Visual Studio!`
 would be my suggestion!

(Now 23 % more awesomer!)

**Comment by bmoore-msft** [comment]
I updated it to match Dev11 and Dev12
