### ISSUE TITLE
Latest build won't install on VS2013

### ISSUE THREAD

**Issue by gwojan** [microsoft/poshtools#258]
I was trying to test the latest build against issue #207 and uninstalled the previous version. Now when I try to install the new version I receive **`This extension is already installed to all applicable products.`**

How can I force VS to re-install?

**Comment by ASayre** [comment]
Hi @gwojan !

We very recently fixed up build-to-build upgrades.  Is it still an issue here: https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts ?

If it's still an issue, could you post the installation log/error?

Thanks!

**Comment by gwojan** [comment]
Thanks @AndreSayreMSFT! 

The latest bits work great so far. Strangely, the build I was trying to install must've been from just a few hours before those were published.

**Comment by gwojan** [comment]
I guess I spoke too soon... Since installing last night's build I'm getting:

![image](https://cloud.githubusercontent.com/assets/6855215/6741493/3c02fc02-ce5e-11e4-8c37-72d0d0eb6763.png)

periodically when trying navigate from tab to tab. Actually any type of keyboard command to open a menu, move to Solution Explorer, etc causes this. I do use VsVim but I haven't been able to determine if there is an interaction yet.

**Comment by ASayre** [comment]
This is an issue in #245 and #246 ;  It's fixed in :  https://github.com/Microsoft/poshtools/pull/260  Once that PR gets merged in, this should fix that issue that you're seeing!

@HuanhuanSunMSFT

**Comment by gwojan** [comment]
Sweet! Thank you!

**Comment by ASayre** [comment]
@gwojan Would you be able to confirm that the (now) latest build fixes up your issue? We've merged it in!

**Comment by gwojan** [comment]
@AndreSayreMSFT I've installed the latest build on my laptop at home and so far so good. :smile: This laptop never had the version on it that I had problems with.

I'll confirm with my work laptop in the morning -- that's the one I was experiencing the problems on.

**Comment by gwojan** [comment]
@AndreSayreMSFT Just to confirm, I've tried the latest bits on the machine I was having problems with and everything seems to be good. Thank you.
