### ISSUE TITLE
Ctrl-Shift-P is taken

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#266]
It's taken by the phone emulator launch [only sometimes installed.]

How about we use Ctrl-Shift-P-S [Get it?  **P**ower**S**hell?] or Alt-P which is only otherwise in use in the Image-drawing context as a shortcut for fill-ellipse?

**Comment by adamdriscoll** [comment]
I like Ctrl+Shft+P+S

**Comment by ASayre** [comment]
After playing with it, it'll be weird and take up too much space for [Ctrl-Shift-P,Ctrl-Shift-S], and will interfere with other starting with Ctrl-Shift-P :(

We're thinking of Ctrl-Shift-\; this one is completely non-taken.  [And it looks powershell-y!]

**Comment by adamdriscoll** [comment]
Sounds good! It does look powershell-y.
