### ISSUE TITLE
No intellisense in REPL window when debugger breaks

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#282]
If user type command in REPL window when the VS breaks into debugger, the intellisense does not work because GetCommandCompletionList still try to execute cmd in runspace, which has already been put into state that "only available for nested pipeline". Only debugging command can be sent to runspace to execute at this point.

**Comment by ASayre** [comment]
Is this the same as #113  ?

**Comment by ericdevg** [comment]
Oh yeah, it is same thing. Close as a dup.
