### ISSUE TITLE
Prompt is not updated with prefix [DBG] when we breaks into debugger

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#285]
Powershell does update the prompt with prefix [DBG] during debugging, we just not refreshing the prompt while debugger break.

**Comment by ASayre** [comment]
Is this a regression of prompt-setting in general?  A simple custom prompt no longer works.

`function prompt { Write-Host "Hi"; return "New Prompt" }` no longer works.

Edit: disregard; The host process had gotten into a broken state [still trying to track it down] but unrelated to this.

**Comment by ericdevg** [comment]
This issue itself is not a regression as it was never there before.

**Comment by ASayre** [comment]
@EricMSFT Agreed; I edited my original post :) [As note, custom prompts by setting the prompt func do work currently].
