### ISSUE TITLE
Input/Output from standard Console doesn't show in REPL

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#287]
Standard Console output isn't passed back up to the REPL Window.  Instead, it's displaying only in the PowerShellHost process.

To repro, create a standard [C#] console app.  Run this from the REPL Window.  Observe that there is no output in the REPL Window, but, if in debug mode, we notice it in the Host output.

![image](https://cloud.githubusercontent.com/assets/10080679/6797905/e66eccb6-d1c4-11e4-871c-e0024acc9eb8.png)

We should also handle input otherwise it locks up the PowerShell host [as we wait in the host for a response.]  Can easily repro using Console.Read[Line|Key]

For consideration/P2: Any colors that are set should be bubbled up to the REPL Window as well.

We have hooks inside PowershellServiceHost.cs for Notify[Begin|End]Application()

**Comment by vors** [comment]
:+1: 
It's the second big missed piece of  [PowerShell Interactive Window as a fully function shell] #291

**Comment by ASayre** [comment]
Added notes about supporting input, especially as our waiting-for-input essentially locks up the host.

**Comment by ASayre** [comment]
Moved this chunk into April
