### ISSUE TITLE
[PowerShell Interactive Window as a fully function shell] Add $profile

### ISSUE THREAD

**Issue by vors** [microsoft/poshtools#291]
PoshTools could be used as a fully functional shell: run anything from Interactive Window, instead of `powershell.exe` / `powershell_ise.exe`!

To allow it, few things would help, I want to start with a simple one:
Add [$profile](https://technet.microsoft.com/en-us/library/hh847857.aspx) and load it on start.

-Sergei
Windows PowerShell team.

**Comment by adamdriscoll** [comment]
PoshTools has it's own profile script if that would help. Try putting PoshTools_Profile.ps1 in that same place you put other profiles. I'm not sure why I made it a seperate file...

**Comment by adamdriscoll** [comment]
That said, it's probably not following the standards in that document you linked. I need to read through that. We're just executing that script, if available, on start up.

**Comment by vors** [comment]
Cool, that's the half of the solution! We just need to add $profile variable, like in other hosts.

**Comment by vors** [comment]
Also, I tried and cannot make it work. I place it in
`C:\Users\sevoroby\Documents\WindowsPowerShell\PoshTools_Profile.ps1`

**Comment by adamdriscoll** [comment]
Maybe it has something to do with the work to move the host out of proc. Not sure where the code to run that script lies. Will have to take a look though!

**Comment by ASayre** [comment]
@vors Thanks for reporting this!  In the other PowerShell hosts, is `$profile` just a string that points to the specified path?

**Comment by ASayre** [comment]
@adamdriscoll I can see cases where each host has a separate profile being a good thing :)  Imagine the  poshTools profile having references to $dte vs the ISE's profile having references to $psISE, etc

**Comment by gwojan** [comment]
For the sake of consistency I think the shell should support all `$profile` variants. At the very least I would like to see `$PROFILE.AllUsersAllHosts` and `$PROFILE.CurrentUserCurruntHost` supported.

**Comment by vors** [comment]
@AndreSayreMSFT absolutely! PowerShell profiles have built-in support for such [separation](https://technet.microsoft.com/en-us/library/hh847857.aspx). `$profile` variable is a little bit magic: it contains different profiles, but by itself points to `$profile.CurrentUserCurruntHost`. 
![image](https://cloud.githubusercontent.com/assets/816680/6831247/5b743b5a-d2dc-11e4-9e31-5ff9cacb4375.png)

**Comment by ASayre** [comment]
Little bit of digging, as to why I couldn't find the children properties with  `$profile.GetType()` returning a string.  

The specified children host values, are added as NoteProperties [Impl. notes: `Add-Member NoteProperty name value -passthru` to the string. `$profile | get-member *` for info.]

For proper implementation of this, we would need to add 

```
    Description                Path
    -----------                ----
    Current User, Current Host $Home\[My ]Documents\WindowsPowerShell\OURPROFILE_profile.ps1
    Current User, All Hosts    $Home\[My ]Documents\WindowsPowerShell\Profile.ps1
    All Users, Current Host    $PsHome\OURPROFILE_profile.ps1
    All Users, All Hosts       $PsHome\Profile.ps1
```

with this mapping:

```
    Name                               Description                
    -----------                        -----------
    $Profile                           Current User,Current Host  
    $Profile.CurrentUserCurrentHost    Current User,Current Host  
    $Profile.CurrentUserAllHosts       Current User,All Hosts     
    $Profile.AllUsersCurrentHost       All Users, Current Host    
    $Profile.AllUsersAllHosts          All Users, All Hosts       
```

@vors : Do you have information on what `The profiles are listed in precedence order. The first 
    profile has the highest precedence.` in the docs mean?  Does that mean that only one is loaded, but if that one isn't found, it keeps trying the subsequent ones until it does find one?

**Comment by vors** [comment]
All of them are applied. It's just determine the order. The order is (by experiment):

```
Hello from All User, All hosts
Hello from All User, Current host
Hello from Current User, All hosts
Hello from Current User, Current Host
```

**Comment by pcgeek86** [comment]
@AndreSayreMSFT @adamdriscoll Just chiming in with a "me too." I feel as if profile scripts are generally considered to be available in an interactive PowerShell host, especially a full-fledged IDE like Visual Studio.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
