### ISSUE TITLE
Stopping the PowerShell host process locks up VS on execution

### ISSUE THREAD

**Issue by adamdriscoll** [microsoft/poshtools#293]
I tried to kill the PowerShell host process to unlock my C# assembly (related to #292). After doing this I tried to launch my script. Visual Studio locked up and stated that it was busy. 

![vsbusy](https://cloud.githubusercontent.com/assets/1256531/6817061/b50c2df8-d269-11e4-9835-7eccc30dfa55.png)

**Comment by ASayre** [comment]
Regression
