### ISSUE TITLE
[Random]Output logging formatting issue for its first script run

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#295]
![image](https://cloud.githubusercontent.com/assets/10080679/6820483/bf04f704-d28c-11e4-8dcc-d7ef89cf7b61.png)

Do not yet know root cause, but I hit it when executing script from soln explorer.  Not consistent repo.

Potentially related race condition:

![image](https://cloud.githubusercontent.com/assets/10080679/6820509/325a3a52-d28d-11e4-975f-d03423a2912c.png)

The script, when run multiple times, generated the above output.  Notice the `HelloHello` without a prompt showing up between them.

**Comment by jinglouMSFT** [comment]
I cannot repro this with the PoshTools build from 3/25/2015 and Powershell v5 Nov. preview. But while trying to repro this bug, I logged two new bugs mentioned above.

**Comment by ericdevg** [comment]
The logging part is still repro and only for the first time execution after launching VS.
