### ISSUE TITLE
Allow PowerShellTools console host to use PSReadLine module.

### ISSUE THREAD

**Issue by gwojan** [microsoft/poshtools#296]
I'm not sure how feasible this is but I would really like to see the PoshTools console behave like a real console and allow `PSReadLine` for redefining the keyboard experience in the shell. @izybkr and @srdubya have done a really amazing job.

With PoshTools in VS and PSReadLine in the console I have quite literally given up using the PSIse...

**Comment by ASayre** [comment]
@gwojan Thanks for the feedback & suggestion!  Do you think this would be covered by #230?

**Comment by gwojan** [comment]
@AndreSayreMSFT, yes, I think that would cover it. My understanding is any host that provides a **real console** can support PSReadLine. The PSIse doesn't provide the hooks so PSReadLine doesn't work.

**Comment by ASayre** [comment]
closing out as dupe :)
