### ISSUE TITLE
Versioning info appears twice

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#302]
We show up in the About dialog under 1.0, and under the tools -> Extensions and Updates menu.  The global VS about dialog has incorrect information.  We should follow the pattern of most other extensions and only show up under the Tools->E&U menu.

**Comment by gwojan** [comment]
@AndreSayreMSFT, I don't think putting the version information only on the `Tools->E&U` dialog is the correct approach.

The correct version information should be also be in the global VS `About` dialog, IMHO. There are many cases where I need to submit a bug report and I need to `Copy Info` to show the Installed products.

That being said, if there is another way to export a list of all the installed products/extensions I'd be good with that too.

**Comment by ASayre** [comment]
@gwojan Unfortunately, the information that currently shows up there has never given a complete picture.  Even without this extension installed, it shows the Version of the CommonAzureTools, And this extension at 1.0.

As we're an extension, we should match the majority of other extensions that could also show up in E/U, and I'd presume you'd want your log to have all extensions anyways :)

I've got a solution for you though!  Courtesy of [this](http://blogs.msdn.com/b/visualstudio/archive/2010/02/19/how-vsix-extensions-are-discovered-and-loaded-in-vs-2010.aspx) blog post, you can run `devenv.exe /log C:\PickAPathHere.xml`

Does that help?

**Comment by gwojan** [comment]
@AndreSayreMSFT, that kinda, sorta helps. :wink: I'll figure something out, thanks.
