### ISSUE TITLE
debugging through pipeline does not show which part of the pipeline is executed

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#303]
When using F11 to go through a statement like:

$JsonParameters = $JsonContent | Get-Member -Type NoteProperty | Where-Object {$_.Name -eq "parameters"}

The cursor does not show which part of the pipeline is current - it's always at the beginning of the line - so the behavior is that you press F11 multiple times but VS never appears to step to the next statement.

**Comment by ASayre** [comment]
Could this be related to #181 ?

**Comment by ASayre** [comment]
[Investigate, we move if needed after investigation]

**Comment by ericdevg** [comment]
The column of breakpoint is supported on powershell, rough estimate this is probably 2 dev-days task.
