### ISSUE TITLE
intellisense exception IndexOutOfRange

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#305]
got this from the activity log while using REPL window

System.IndexOutOfRangeException: Index was outside the bounds of the array.&#x000D;&#x000A;   at PowerShellTools.Intellisense.PowerShellCompletionSet.SelectBestMatch()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Match()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.OnViewBuffer_Changed(Object sender, TextContentChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

**Comment by bmoore-msft** [comment]
ok, I think I might have a repro:
- bring up REPL
- type "switch" (wait a few seconds for intellisense to catch up)
- type "-"
- press tab to use intellisense
- spacebar
- tab, wait for intellisense, tab again, tab again

**Comment by ASayre** [comment]
Also have a 100% repro: Try typing:

`$dte.a` and observe crash.
