### ISSUE TITLE
F5 without any breakpoints set stopped at a random line per file 

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#306]
![f5](https://cloud.githubusercontent.com/assets/10081208/6857149/fea109ee-d3c1-11e4-9d05-f7e4cbdd58c1.png)

**Comment by ericdevg** [comment]
Do we have a consistent repro? or any repro steps help to get a random repro?

**Comment by ASayre** [comment]
no repro

**Comment by jinglouMSFT** [comment]
This is a dup of #322 which Eric has already fixed.
