### ISSUE TITLE
PSVS execution with parameter with UI support

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#34]
Partner is more looking for leveraging on PSVS to execute a PS script, however, only way to provide parameters for script to run is through REPL window(interactive window), which may not be desirable experience for partner.

**Comment by AndreSayre** [comment]
Related to adamdriscoll/poshtools#120 - We can hook into Prompt for this functionality

**Comment by ericdevg** [comment]
Yes, by having prompt could be the way to expose this functionality if we'd like to avoid UI stuff. Just note that by default powershell prompt only asks required parameters, while normally partner is expecting a way to execute their script with a certain set of parameters, so that's going to be the work for solving this issue in order to meet the actual customer needs.

**Comment by bmoore-msft** [comment]
Is this just Show-Command?  (not real clear on the scenario, seems different than the linked issue above)

**Comment by ericdevg** [comment]
It is somewhat related with prompt, however prompt only serves for the mandatory required parameters. I guess the ask here is more related with #170
