### ISSUE TITLE
Create pending breakpoint crash VS 

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#345]
![capture1](https://cloud.githubusercontent.com/assets/10081101/6974138/eb379f98-d944-11e4-9a54-156f61956e2b.PNG)

Trying to load .net assembly in my powershell script, always got error from creating pending bp, and crash VS.
`[Reflection.Assembly]::LoadFile("C:\Users\zhiyd\Documents\Visual Studio 2013\Projects\PowerShell Script Project1\ClassLibrary1\bin\Debug\ClassLibrary1.dll")
$mathInstance = new-object ClassLibrary1.Methods
$mathInstance.Product(10, 2)
`

**Comment by ericdevg** [comment]
Turn out nothing to do with the assembly loading stuff, it is somewhat related with this specific project itself, not yet found any trigger for this issue yet, but I got 100% repro on my project.

**Comment by ericdevg** [comment]
Repro lost after I removed some breakpoint from one file...

**Comment by jinglouMSFT** [comment]
No repro anymore.  Please reactivate if you run into the issue again.  Thanks.
