### ISSUE TITLE
autocomplete getting in the way in REPL

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#348]
in REPL type "cd \" and hit enter - instead of completing the command, we complete autocomplete and that fills in a different value then backslash.  The only way to actually get the \ is to esc autocomplete.  I think the fix here is to not automatically select an item in the autocomplete list but wait for a tab or arrow key to start list selection.

**Comment by ASayre** [comment]
to append to this:  Not automatically select if it doesn't match anything in list slection.

if we do cd C:\Win and hit enter, we expect it to Autocomplete to C:\Windows

eg:

![image](https://cloud.githubusercontent.com/assets/10080679/6974446/a9eb7142-d947-11e4-803c-7e4edc290ac6.png)

$Recycle bin should NOT be automatically selected, as it doesn't match what's been typed.

**Comment by ejizba** [comment]
I think this issue needs a little more refining.  For example, the first item should be selected in the following case, but now it's not:
![intellisense](https://cloud.githubusercontent.com/assets/11282622/7188086/1d255d2a-e42a-11e4-936f-097caff20c4d.png)

**Comment by ASayre** [comment]
Original chunk of this has been, fixed, refinement pushed out to May timeframe.

Anyways, good catch on this, @EricJizbaMSFT !  We do differ from ISE here. Especially since we still auto-select the first one on member variables. [eg, `$myVar.`]
