### ISSUE TITLE
[TrackingItem] Redirection templates shown while posh tools installed.

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#350]
![capture](https://cloud.githubusercontent.com/assets/10081101/6974566/ad71ca0e-d948-11e4-809c-42fd518ae8f4.PNG)

Version 14.0.22728.1 D14REL

EricJ mentioned that it should be fixed in latter builds of VS, put a tracking item here that we need verify it.

**Comment by ASayre** [comment]
Fixed
