### ISSUE TITLE
tab on autocomplete with no match inserts a tab character

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#353]
in REPL and the editor when you hit tab with the autocomplete list open, and there is no match a tab char is inserted.  In this case the autocomplete list should just close.

this also happens when tab is used to "trigger" autocomplete - I think that may be tracked in another issue, but tab should bring up the autocomplete list when on a command or the params for a command

**Comment by ASayre** [comment]
Related to https://github.com/adamdriscoll/poshtools/issues/13  and https://github.com/adamdriscoll/poshtools/issues/14

**Comment by HuanhuanSunMSFT** [comment]
Just to clarify. If you type write- , there are completions like Write-Debug, Write-Host, etc. Should the first one, say Write-Debug, be selected? In ISE, it's selected. 
@bmoore-msft @AndreSayreMSFT

**Comment by bmoore-msft** [comment]
Whenever the autocomplete list opens and there is no better match, the first should be selected and then filtered as typing continues

tab will cycle through the autocomplete list even when the list is not open, e.g. type:
Set-A[tab][tab][tab] - that will cycle through the set-\* cmdlets.  That tab cycling should work on params, param values, etc.

So that's a little beyond "don't insert the tab char" but it's what should happen instead.
