### ISSUE TITLE
REPL stops executing commands

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#354]
I don't have a magic repro for this but I ran into it on 2 different machines on build 647.  At some seemingly random point the REPL window decides to stop executing commands, just immediately returns to a prompt.  The only common piece I can discern is that it happens after some command that is meant to write something to stdout and whatever it is doesn't get written.  I _think_ in both cases, the actual result of the command was going to be "empty".  That's the best I got, maybe someone else will find this and have a better repro or a "me too".

**Comment by ASayre** [comment]
@bmoore-msft Do those items and commands expect something from std-in?  ie, May be related to #287 ?

**Comment by bmoore-msft** [comment]
no - I've run into this problem just trying to change directories.  Launch REPL, start doing cd's to get to a certain path and it just stops cd'ing.

**Comment by ericdevg** [comment]
I m not sure if it could be related with the stdout thing, which breaks the channel from some point for some reason, it might be worth to give it another try on incoming dev build, where I just merged my fix for stdout/stdin. @bmoore-msft

**Comment by jinglouMSFT** [comment]
no repro in the latest builds. closing for now. Please reactivate if you run into this issue again. Thanks!
