### ISSUE TITLE
Versioning for powershell host service app?

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#358]
![capture2](https://cloud.githubusercontent.com/assets/10081101/6990389/f9e3d59e-da1f-11e4-9152-a894c23bdc83.PNG)

**Comment by ASayre** [comment]
The 1.2.3.4 versions are applicable only upon Dev Builds; on the builds spit out by AppVeyor, they should match the build numbers there.  Is that what is expected, @EricMSFT ?

**Comment by ASayre** [comment]
Although, File Description, we'll want to update that to something more human-friendly :)

**Comment by ericdevg** [comment]
Oh sounds good to me, as long as official build number is fine. 
And I agree that it'd good to have human-friendly description.
