### ISSUE TITLE
I'm still observing the first intellisense trigger runs over 20s

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#364]
![capture2](https://cloud.githubusercontent.com/assets/10081101/7051832/c9634698-dddf-11e4-9f9d-eb92693081e3.PNG)

It can not be stopped/cancelled even from the runspace perspective, which blocking the execution if you runsomething during that period.
Not sure which part slows it down, it might be due to the GetCompletionList, if that is the case, we should understand the reason(or bug?) behind it.

**Comment by AndreSayreMSFT** [comment]
Thinking out loud: Is

**Comment by adamdriscoll** [comment]
We actually had a discussion on the MVP DL about this happening in the ISE as well. I've experienced it from time to time in any PowerShell host. Might want to reach out to the PowerShell team to see what's up. I would imagine having a lot of modules installed and a large PowerShell profile could add to it but I'm not entirely sure what it's doing for so long. Any specific PowerShell version you guys are using?

**Comment by ericdevg** [comment]
(not always repro)
First time load VS, in REPL, type:

> Write-
> [Debug]getcompletionliststart:4/9/2015 6:25:12 PM
> [Debug]getcompletionlistfinish:4/9/2015 6:26:30 PM; matchnumber:12

This debugging log are just ahead and after the call: 
`
commandCompletion = CommandCompletion.CompleteInput(ast, tokens, cursorPosition, null, _currentPowerShell);
`
This is likely a powershell bug, and for now we just need make a tactic fix to avoid that cold start.
