### ISSUE TITLE
Show the Script/Commands executed in REPL when run from editor

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#367]
When I run a command/script via the host, the output is redirected to REPL.  This is nice, but I don't see the command that was executed that generated all of that output.  I can't tweak it and try again without going through the host.

This is slightly different than the ISE.  The ISE shows the command but it's not part of command history - this feels like the correct behavior.  I can see the command(s), I can copy paste and now make them part of REPL command history and modify, etc.

Feels like we should follow suit here, but worth discussion for sure.

**Comment by ASayre** [comment]
Do you have an example?  I don't understand how it differs yet :)

**Comment by bmoore-msft** [comment]
In the ISE, run a script that's loaded by pressing F5.  You'll see the command line in REPL echo the command that is run by pressing F5, i.e. the full path of the file.

In poshtools, we don't echo the command though we do echo the output from the host.  So we have a bunch of output over in REPL, but no indication where it came from.

Somewhat related, we also echo the output _above_ the command prompt.  We should probably disable the command prompt during that execution since we don't allow another pipeline when the host is running.

**Comment by ASayre** [comment]
Oh, you mean running it via F5/Editor?  It doesn't put it into the command history [eg, pressing up] in the ISE Repl, but you're right in that it does display the entirety of the script in the REPL as if it were input.  I think we should display _something_ in the REPL Output, but I'm not too keen on the entirety of the script.  Imagine a large script there.  How useful would that be?

**Comment by bmoore-msft** [comment]
yeah F5/Editor - I think we should put the command the was executed... so if the command was:
c:\foo.ps1 -someparam "value"
we put that...

But a host called could also submit a script in-line (i.e. multiple lines and not from a file) - we probably need to be consistent and show that too - i.e. show what created the output (ISE does this for scripts that are not save to disk yet).

It could be monstrous but we should be predictable/consistent

**Comment by ASayre** [comment]
First part in most cases, wouldn't have any params, given that when we run stuff from the editor, we just run it and push out any prompts when we get a response from the Host.

We should mirror the ISE though for running from a saved file :)  
![image](https://cloud.githubusercontent.com/assets/10080679/7099049/8f545c28-df9f-11e4-81a0-7118ef064105.png)

This is where there's something different though: if the File is unsaved in the ISE, it'll run the whole thing in the REPL on F5.  However, we always force a save.  I think we should continue always forcing a save.

ISE:
![image](https://cloud.githubusercontent.com/assets/10080679/7099058/c16a8692-df9f-11e4-8425-5de91cbe0152.png)

**Comment by bmoore-msft** [comment]
For the interactive scenarios (e.g. F5) I think forcing a save is a good idea (consistent & VS behavior).

**Comment by ASayre** [comment]
Tweaked title a bit now that we've figured out we want to do!

**Comment by bmoore-msft** [comment]
Cool - but remember there are 2 scenarios here: 1) from editor and 2) from host
