### ISSUE TITLE
enter key in repl brings up autocomplete (it should complete autocomplete)

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#371]
open REPL, start typing... notice the blazing fast autocomplete window (I can't help talking about that, but that's not what this is about).

When you hit enter, it should select the selected item (if any) in autocomplete and then a subsequent enter should execute the command.  The subsequent enter doesn't though, it brings back up the autocomplete window.

Build 711

**Comment by ASayre** [comment]
![image](https://cloud.githubusercontent.com/assets/10080679/7079600/0373b362-dedb-11e4-8bd4-77f0e6f9fa85.png)
 Hit enter at EOL
