### ISSUE TITLE
PowerShellToolsProcessHost visible when launching Visual Studio

### ISSUE THREAD

**Issue by gwojan** [microsoft/poshtools#384]
When I launch Visual Studio a small console window, which I'm guessing is `PowerShellToolsProcessHost`, flashes in front of VS and steals focus from the VS gui.

Please hide this window if possible...

**Comment by ASayre** [comment]
@gwojan : It's bugging us too! We've been looking at it, and there isn't a non-trivial fix for it yet.  We're investigating other avenues to not have it briefly appear but still retain all other functionality.
