### ISSUE TITLE
cannot change to parent dir

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#395]
related to #348 you cannot cd to the parent directory because autocomplete will fill in some .\ value..

in repl, just try typing cd ..

**Comment by ASayre** [comment]
Related to #396 

This looks like it was fixed with PR https://github.com/Microsoft/poshtools/pull/393 ; confirm?
@bmoore-msft

**Comment by bmoore-msft** [comment]
cd .. (with a space) does work in build 790.

hit #396 right away but will close this one
