### ISSUE TITLE
Type "cd.." in REPL having intellisense and autocompletion triggered so it becomes "cd..."

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#396]
which is pretty annoying to me.

**Comment by ASayre** [comment]
Note: This is when there's no space between cd and ..

**Comment by ASayre** [comment]
@HuanhuanSunMSFT Is this a simple fix?

**Comment by HuanhuanSunMSFT** [comment]
Should be a quick fix. I'm on it. @AndreSayreMSFT @EricMSFT
