### ISSUE TITLE
Empty breakpoint will cause off-by-one-breakpoint

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#445]
![image](https://cloud.githubusercontent.com/assets/10080679/7227498/02e77914-e706-11e4-9182-18e0af5a54fa.png)

Stopped here initially.

related to #75

**Comment by ericdevg** [comment]
Note that "off by one" is the powershell debugger engine behavior, the same as ISE, if you try to set breakpoint on a powershell comment, it will break next line.

**Comment by ASayre** [comment]
Because of VS/PowerShell behavior.
