### ISSUE TITLE
Waiting a while when sitting on a breakpoint in the middle of F5 and returning hangs VS

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#458]

**Comment by ericdevg** [comment]
@AndreSayreMSFT  How long time did you wait for last time when you repro this? I waited for >2hrs, and I don't see problem on proceeding the debugging. could be something else?

**Comment by ASayre** [comment]
@EricMSFT  It wasn't quite two hours, but definitely moving laptop around, closing/opening, having it sit, etc.  I'll see if I can get a repro again

**Comment by ASayre** [comment]
May be related to #448
