### ISSUE TITLE
Add an option to disable Tab triggering IntelliSense

### ISSUE THREAD

**Issue by pshamus** [microsoft/poshtools#474]
Typing in something simple like $var< Tab > = "1" no longer inserts a tab character after the word $var. Instead I see that IntelliSense is kicking in trying to perform a match. The behavior seems to be like the ISE instead of VS. I use tabs to align various indented commands.

I was running 3.0.108 and experienced the issue, then updated to the latest nightly build and it still persists.

**Comment by pshamus** [comment]
FYI, it appears that version 3.0.99 has the correct (desired) behavior.

**Comment by gwojan** [comment]
I just noticed the same thing. I was trying to align some values in an enumeration...

**Comment by HuanhuanSunMSFT** [comment]
Hi @pshamus and @gwojan, thanks for reporting this.
We added this feature of using TAB to trigger IntelliSense unless current line is all blank just like ISE. We tried to align PowerShell tools experience with ISE.

**Comment by pshamus** [comment]
That's a real bummer.  I was hoping to have the same type of experience VS has with native (C#, VB.NET, etc.) files.  This is one of the main reasons why I can't stand (and don't use) the ISE.  Is there any chance to have that re-enabled?  Code formatting, especially in PowerShell, is crucial for our team.  We are managing over 45,000 lines of PowerShell code in 30+ modules.

**Comment by HuanhuanSunMSFT** [comment]
@pshamus We can certainly add an option to disable TAB triggering IntelliSense. I'll put this to TO-DO backlog. Thanks.

**Comment by pshamus** [comment]
Any chance this issue can have an increased priority? I am running an old version and would like to be more up to date with the bug fixes while maintaining this functionality.
