### ISSUE TITLE
Right click in editor or Solution Explorer should support input parameters

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#482]
This is a feature request.  When I debug my build script I need to provide the following parameters.
.\BuildRelease.ps -name "IoT" -release -skiptests -skipcopy -skipdebug.  It would be nice if I could open BuildRelease.ps in the VS editor and set breakpoints where I need to debug, then right click in the editor to execute the script with parameters with a menu selection such as "Execute script with parameters", and prompt me for entering the parameters.  As of today, I will have to create a PS project to do so, a bit overkill.  
Same suggestion for Solution Explorer.

**Comment by ASayre** [comment]
![image](https://cloud.githubusercontent.com/assets/10080679/7404879/e416d502-ee9e-11e4-8c4a-4417a7aced8c.png)

**Comment by ASayre** [comment]
Fixed by @HuanhuanSunMSFT in #502

**Comment by HuanhuanSunMSFT** [comment]
I assume we can close this one? @AndreSayreMSFT @jinglou-

**Comment by ASayre** [comment]
Closed!
