### ISSUE TITLE
REPL window is eating confirmation prompts

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#490]
the repl window is eating confirmation prompts.

c:>md foo
c:>rd foo -confirm

You won't get a prompt.  This also happens with -Force params which can be pretty destructive.

**Comment by ASayre** [comment]
Dupe of https://github.com/adamdriscoll/poshtools/issues/120 ?  Given the lack of prompt for these types of, I think we should bump up the priority :)
