### ISSUE TITLE
Single/double Quote-Completion does not work as expected

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#497]
[I think we discussed this in Standup?]

Type `Write-Host "Potato"` Instead we end up with `Write-Host "Potato""`

Also repros with single quotes as well.

**Comment by gwojan** [comment]
I just noticed something interesting. If the string is inside square brackets the quotes complete/terminate correctly but then I end up with an extra closing bracket.

``` Powershell
files['test one']]
```

However, if the line starts with a `$` the old behavior is seen.

``` PowerShell
$files['test two'']
```
