### ISSUE TITLE
We shouldn't include update notifications in Blend for Visual Studio

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#524]
To repro:
1. Install VS 2015 RC
2. After setup complete, launch Blend for Visual Studio 2015
3. You will notice a notification flag in the upper right corner of the Blend IDE
4. Click on the flag and it tells you there is a PowerShell Tools update available
5. Click to install the update.
6. VSIX errors. 

We should only limit our notifications to the VS SKUs (Community, Pro+)

![blend-notification](https://cloud.githubusercontent.com/assets/10081483/7545217/dc32ceb8-f588-11e4-8938-a083ef63c5b6.png)

**Comment by ejizba** [comment]
Also reproed for this extension:

![blendnotification](https://cloud.githubusercontent.com/assets/11282622/7545778/956400ac-f58c-11e4-8dc4-b97f8a8daa1d.png)

![blendextensionerror](https://cloud.githubusercontent.com/assets/11282622/7545781/9b795622-f58c-11e4-9ddc-75d7556ba3fb.png)

**Comment by ASayre** [comment]
This looks to be a bug in VS -- @jinglou- was creating the bug internally [1169322]

**Comment by ASayre** [comment]
Fixed internally.
