### ISSUE TITLE
Variable watching is missing some properties on objects returned from ConvertFrom-Json

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#531]

**Comment by ASayre** [comment]
Which properties/example?

**Comment by ASayre** [comment]
Follow up w/Miguel for more Info.  The Object returned is not showing up.

**Comment by ASayre** [comment]
@HuanhuanSunMSFT I talked w/Miguel, and we wouldn't get a repro -- However, he said you were able to isolate a repro?

**Comment by ASayre** [comment]
Per convo, no repro from Miguel.  He'll reach out if he runs into it again.
