### ISSUE TITLE
Input some GB18030 Character as  " ɑɡ〇〾⿻⺁䜣€" will show different words

### ISSUE THREAD

**Issue by v-jannwa** [microsoft/poshtools#535]
Input words :  ɑɡ〇〾⿻⺁䜣€
Actual show below words:
![gb18030](https://cloud.githubusercontent.com/assets/12421590/7629990/33812004-fa64-11e4-9d60-b4970c5a5322.png)

**Comment by ASayre** [comment]
Thanks for reporting this, @v-jannwa !  Given that this shows up in this dialog even with other projects, did you want to open a bug internally in the underlying project creation dialog area?

**Comment by ASayre** [comment]
@HuanhuanSunMSFT follow up with CTI to log against VS-Proper.

**Comment by v-jannwa** [comment]
We have filed a bug #953383 in TFS with other projects, but it is resolved as Won't Fix. So is this Won't Fix for PowerShell script project? If yes, you can close this issue.

**Comment by ASayre** [comment]
Closing as such!
