### ISSUE TITLE
Auto-complete should not occur in comments part

### ISSUE THREAD

**Issue by v-jannwa** [microsoft/poshtools#537]
1. Open the ps1 file.
2. Input '(' in comments part.

Expect: Anto-complete should not occur in comments part
Actual : 
![auto-complete](https://cloud.githubusercontent.com/assets/12421590/7630129/c00d2418-fa65-11e4-8237-a733e601bca0.png)

**Comment by HuanhuanSunMSFT** [comment]
Fixed in PR #608
