### ISSUE TITLE
Remote debug can't hit the breakpoint in remote files

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#538]
Config:
Dev14 Ent RC + latest PoshTools (http://aka.ms/Get-PoshToolsNightly)

Repro Steps:
1. Connect to a remote machine through "Enter PowerShell Session” icon in the REPL window
2. Open remote file and set a breakpoint
3. F5
4. Verify breakpoint can be hit.

Expected: Breakpoint can be hit.

Actual: Can't hit breakpoint. Please see below screenshot:
![breakpoint](https://cloud.githubusercontent.com/assets/12443209/7630189/5ba120f0-fa66-11e4-959b-1740551bc7d4.PNG)

More Info:
Also repro in Dev12.

**Comment by ericdevg** [comment]
@v-hedli Thanks for reporting this issue. Looks like there was an fatal error happened before you open Log.ps1 to debug (as the output: there is a problem in powershell host service), would you be able to:
1. provide how did you run into the error message
2. try restart VS and do a fresh new remote session debugging, and see if you can have breakpoint hit.

**Comment by v-hedli** [comment]
1. There is this error message because i didn't install powershell 4.0 in my remote machine [which be installed in local machine]. After installing the powershell 4.0, this error is gone.
2. Fixed above issue and install the latest PoshTools (http://aka.ms/Get-PoshToolsNightly), remote session debugging works well and breakpoint can be hit.

**Comment by ASayre** [comment]
re: PowerShell on remote machine... potentially related to https://github.com/Microsoft/poshtools/issues/194 ?

**Comment by v-hedli** [comment]
As my last comments said, now the issue has been resolved. Thanks Eric and Andre for looking into this.
