### ISSUE TITLE
The comments part should not set the breakpoint in ps1 file

### ISSUE THREAD

**Issue by v-jannwa** [microsoft/poshtools#539]
1. Open the ps1 file in PowerShell project.
2. Add some breakpoint in comments part

Expect: The comments part should not set some breakpoints.
Actual: 
![breakpoints](https://cloud.githubusercontent.com/assets/12421590/7630216/793d064c-fa66-11e4-9b75-c68e0d9b3dd1.png)

**Comment by ericdevg** [comment]
Thanks for reporting this, #75
