### ISSUE TITLE
After cmd executed completely, the session is still running in REPL window

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#541]
Config:
 Dev14 Ent RC + latest PoshTools (http://aka.ms/Get-PoshToolsNightly)

Repro Steps:
1. Open REPL window and input cmd like sleep 10
2. After the cmd executed completely, verify the session is stopped.

Expected: After the cmd executed completely, the session should stop.

Actual: After the cmd executed completely, the session is still running. Please see below screenshot:
![running](https://cloud.githubusercontent.com/assets/12443209/7630320/7393dff8-fa67-11e4-811d-224276d7f223.PNG)

**Comment by ASayre** [comment]
Thanks for reporting this!  This looks to have the same root cause as #533 - as they have very similar symptoms.
