### ISSUE TITLE
There aren't any warning prompt when enter some unmeaning or wrong characters in editor

### ISSUE THREAD

**Issue by RongTang** [microsoft/poshtools#542]
![nowarning](https://cloud.githubusercontent.com/assets/12443159/7630142/ea830140-fa65-11e4-8b25-fbeba12fe84e.png)

VS: Dev14 Community
OS: Windows 8.1 Enterprise
Repro steps:
1. Install latest version PoshTools from http://aka.ms/Get-PoshToolsNightly;
2. Open VS and create a PowerShell project;
3. Enter some unmeaning characters or make two methods have same name, warning or error prompt will be expected, but actually no any prompt, please see the top screenshot.

**Comment by ASayre** [comment]
Thanks for reporting this!

However, this is by design as 1) We don't know the availability of all commands until run-time. [A module could very well make 'sdfsfs' a valid command] and 2) A function being defined twice _when not inside a class_ is valid PowerShell.

eg,

```
class ABC
{
    Moo()
    {
    }

    Moo()
    {
    }

}
```

should show an error.

**Comment by v-hedli** [comment]
When i defined two functions with the same name in one script project, how to determine which function will be invoked? 
![name](https://cloud.githubusercontent.com/assets/12443209/7768317/7a1ff5aa-00ac-11e5-90ed-98ef5bb35978.PNG)

**Comment by ASayre** [comment]
@v-hedli : In the above example, the second function.  However, in a more general case, it's impossible to tell with 100%, as functions can be redefined at virtually any point.

You can think of the above as setting 'myfun' to its codeBlock twice.  The second one overwrites the first.
