### ISSUE TITLE
Cannot comment-out the selected code from VS tool bar

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#543]
Config:
Dev14 Ent RC + latest PoshTools (http://aka.ms/Get-PoshToolsNightly)

Cannot Comment-out the selected lines from VS tool bar, please see below screenshot:
![commentout](https://cloud.githubusercontent.com/assets/12443209/7630417/5bd45ef0-fa68-11e4-8e6a-ee1fe20397bf.PNG)

**Comment by ASayre** [comment]
Thanks for reporting this!  related to https://github.com/adamdriscoll/poshtools/issues/206
