### ISSUE TITLE
The yellow arrow can't be dragged to previous lines when debugging

### ISSUE THREAD

**Issue by RongTang** [microsoft/poshtools#544]
![yellowarrow](https://cloud.githubusercontent.com/assets/12443159/7630399/35adb730-fa68-11e4-9a5d-c3e9e6b62441.png)

VS: Dev14 Community
OS: Windows 8.1 Enterprise
Powershell: v5
Repro steps:
1. Install latest version PoshTools from http://aka.ms/Get-PoshToolsNightly;
2. Create a PowerShell project in VS.
3.Add some breakpoints and start debug;
4.Try to drag the yellow arrow after hit a breakpoint

Expect: The yellow arrow can be dragged, because it can be dragged in C# code
Actual: The yellow arrow can't be dragged

**Comment by ericdevg** [comment]
Thanks for reporting this, #45
