### ISSUE TITLE
Ctrl+C doesn't work when run long running cmd in PowerShell Interactive Window

### ISSUE THREAD

**Issue by ghost** [microsoft/poshtools#545]
OS: Win Svr 2012 R2 
VS: Dev12 Ent + Update5
Powershell v4 + latest PoshTool

Repro Steps:
1. Open PowerShell Interactive Window
2. Run long running command like sleep 100
3. using <Ctrl>+c to stop run cmd

Actual: <Ctrl>+c doesn't work, still running cmd.

More Info: Repro in all VS

**Comment by ericdevg** [comment]
Thanks for report this, #425
