### ISSUE TITLE
Cannot name a PowerShell Project with string "𠀀𠀁𠀂𠀃𪛑𪛒𪛓𪛔𪛕𪛖"

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#549]
Config:
Dev14 Community RC + Latest PoshTools (http://aka.ms/Get-PoshToolsNightly)

Repro Steps:
1. Launch VS and New Project->PowerShell
2. Input the proejct name "𠀀𠀁𠀂𠀃𪛑𪛒𪛓𪛔𪛕𪛖" in New Project dialog
3. Verify project be created successfully. 

Expected: Project should be created successfully.
Actual: A dialog popped up blocking project creation, please see below screenshot:
![newproject](https://cloud.githubusercontent.com/assets/12443209/7648563/ea8f303a-fb16-11e4-91aa-fbe9b6ba8203.PNG)

**Comment by ASayre** [comment]
Just as with #535, Given that this shows up in this dialog even with other projects, did you want to open a bug internally in the underlying project creation dialog area?

**Comment by v-hedli** [comment]
We have filed a bug #1107153 in TFS with other projects, but it is resolved as by design. So is this by design for PowerShell script project? If yes, you can close this issue.

**Comment by ASayre** [comment]
Thanks for reporting this!  As this is part of a larger Visual Studio item that affects all project types not inclusive of the PowerShell tools, Closing this out here.
