### ISSUE TITLE
<Ctrl>+Space should not enable intelliSense when input path like "Write-"

### ISSUE THREAD

**Issue by ghost** [microsoft/poshtools#550]
OS: Win Svr 2012 R2
VS: Dev12 Ent + Update5
Powershell v4.0 + latest PoshTool

Repro Steps:
1. Create a PowerShell Script Project
2. Input $log = "Write-"
3. Press <Ctrl>+Space

Expect: Won't enable intelliSense
Actual: Enable IntelliSense

![enableintellisense](https://cloud.githubusercontent.com/assets/12426589/7649462/c39fcee0-fb1f-11e4-8b8f-e3873189481c.png)

**Comment by ASayre** [comment]
Regression?  We thought we fixed this :)

**Comment by HuanhuanSunMSFT** [comment]
Fixed in the PR #608
