### ISSUE TITLE
Popup an error dialog when restarting VS after install PoshTools from VS Gallery in Dev11

### ISSUE THREAD

**Issue by RongTang** [microsoft/poshtools#552]
VS: Dev11 Premium+Update4
OS: Windows 7 Enterprise
Repro steps:
1.  Open VS, select 'Tools' -> 'Extension and Updates' in the menu bar, search 'powershell' and install PowerShell Tools;
2. After installation successful, ask for restart VS;
3. Verify restart VS successfully.
Expect: Restart will success and have no error.
Actual: An error dialog pop up, please see screenshot as below.

![untitled](https://cloud.githubusercontent.com/assets/12443159/7649476/f51f7100-fb1f-11e4-9274-4c6b27cb0c2e.png)

More Info:
Just repro in dev11.

**Comment by ericdevg** [comment]
Seems PS3.0+ is absence in this scenario, which I would expect another better formatted error dialog show up.

**Comment by ASayre** [comment]
@RongTang At this time, we're not supporting Dev11; that _may_ change in the future, but no need to spend cycles on that :)  Closing this out as this is a D11 issue.
