### ISSUE TITLE
The state of the parameter list should be unchecked in the parameter dialog 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#566]
The current state by default is in an undefined (equivalent to unchecked) state, a black square. We should have them unchecked if no default values provided. 
![parameter_list](https://cloud.githubusercontent.com/assets/10081483/7760465/8db60b7c-ffd0-11e4-9ebc-c03a532c8eda.png)

**Comment by HuanhuanSunMSFT** [comment]
Close this undefined state is more suitable for a undefined switch parameter
