### ISSUE TITLE
In Execute with params, hintText for unspecified params shouldn't be null

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#570]
We shouldn't list <Null> as watermark/hint text for in the executing with params dialog.

Null has a specific, semantic meaning, and we're not necessarily feeding 'null' into the script.  We should change it to 'Unspecified' [Is this the correct wording that's not <null>?'

**Comment by ASayre** [comment]
Lets just remove the watermark text.

**Comment by HuanhuanSunMSFT** [comment]
Fixed
