### ISSUE TITLE
F5 multiple times, the debug mode will stay running status

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#573]
Config:
Dev12+Update5 + Latest PowerShell Tool (http://aka.ms/Get-PoshToolsNightly) on win8.1 Ent

Repro steps:
1. Launch VS and create a powershell script project
2. Add some code
3. F5 successfully.
4. Repeat F5 and verify F5 successfully..

Expected: F5 successfully. 
Actual: debug mode is always running, unless you stop it via the tool bar, please see below screenshot:
![debugging](https://cloud.githubusercontent.com/assets/12443209/7768121/a11bfade-00aa-11e5-959a-604e2e96fdbd.PNG)

Repro Machine:
Account: redmond\vslab2  IP: 10.110.108.74

**Comment by ASayre** [comment]
@v-hedli Does this still repro with the latest bits?

**Comment by jinglouMSFT** [comment]
@v-hedli Still waiting on repro...

**Comment by v-hedli** [comment]
I have verified this issue with the latest build on both Dev12 and Dev14, it never repro again.
