### ISSUE TITLE
Breakpoint's hit count always is 0 when debugging

### ISSUE THREAD

**Issue by v-jannwa** [microsoft/poshtools#575]
Repro steps:
1. Add some breakpoints for code in Script.ps1 file.
2. F5
3. we can see the Breakpoint's information in Breakpoins window.

Expect: 
when hitting a breakpoint in Editor window, the current hit counts should not 0 in Breakpoint window

Actual: 
The current hit counts is still 0. you can have a look below picture.
![hitcounts](https://cloud.githubusercontent.com/assets/12421590/7768316/7a0284e8-00ac-11e5-9d2c-9b96305916e2.png)

**Comment by MrayerMSFT** [comment]
This does not appear to "technically" be a bug. From what I can tell keeping track of a breakpoint's hit count has never been implemented. So with that in mind, do we want to go ahead and implement this now or later?
