### ISSUE TITLE
After poshtools installed successfully, modify VS, the PowerShell Tools is checked, but the message still showed

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#581]

**Comment by ASayre** [comment]
This seems like a greater, Visual Studio bug that exists outside of PowerShell Tools itself.  @v-hedli , did you want to report it through the standard channels to be handled by the appropriate team?

**Comment by v-hedli** [comment]
Thanks for your comments, I have filed a new bug (BugID: #1178065) in TFS to find the appropriate team to handle this issue.
