### ISSUE TITLE
Regression in PoshTools build v3.0.1145

### ISSUE THREAD

**Issue by gwojan** [microsoft/poshtools#586]
When I load a PowerShell project the main VS UI loses focus forcing me to `Alt+Tab` to regain focus.

**Comment by ASayre** [comment]
@EricMSFT  ?

**Comment by ASayre** [comment]
@gwojan Eric has fixed this up for you!  Many thanks for looking at these builds as we put them out!

Would you be willing to see if https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/3.0.1153 makes things nice for you?  Looks to be as such from our end, but verifying is always good!

**Comment by ericdevg** [comment]
Thanks a lot for reporting this. @gwojan

**Comment by gwojan** [comment]
@EricMSFT Thank you, v3.0.1153 does appear to fix my issue, however v3.0.1155 breaks again. :frowning: 

The other thing I noticed is there is a `PowerShellToolsProcessHost.exe` icon displayed in the `Alt+Tab` preview window. Obviously this shouldn't be there... :wink: In the broken builds that's the _window_ that appears to have the focus instead of Visual Studio. I honestly don't know how long that process has been visible in the `Alt+Tab` list because I don't normally use the default `Alt+Tab` handler. I just happened to install v3.0.1153 on a machine that uses the default handler this time.

**Comment by ericdevg** [comment]
@gwojan  I think v3.0.1155 is not from dev branch, it is just private one which probably haven't pulled my recent change.

For the window shown in alt+tab, that is good found! Thanks again, I m sending out a merge request for fixing that.

**Comment by gwojan** [comment]
@EricMSFT Thank you again! Build 3.0.1158 addresses both of my issues.:smile:
