### ISSUE TITLE
allow callers of poshtools host to set the host - or set it from VS

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#587]
We're thinking of using $host.name to help with telemetry.  When I run a script from REPL or doc window $host is our poshtools string.  However if someone calls into us to run a script, it's a generic string: System.Management.Automation.Internal.Host.InternalHost

Can we either 1) set that host to our poshtools host and/or 2) allow the caller to optionally specify it?

**Comment by ASayre** [comment]
Per convo -- ByDesign -- can use $Host.Name :)
