### ISSUE TITLE
"Get Powershell Tools for Visual Studio" still exist after install PoshTool in Dev14

### ISSUE THREAD

**Issue by ghost** [microsoft/poshtools#604]
Powershell V4 + latest PoshTool from https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/3.0.1198

Repro Steps:
1. Install PowerShellTools.14.0. 
2. Open Dev14 and verify project template for PoshTool

Expect: Just have 2 prowershell project. And no "Get PowerShell Tools for Visual Studio"
Actual:  "Get PowerShell Tools for Visual Studio" still exist.

![poshtoolindev14](https://cloud.githubusercontent.com/assets/12426589/8055366/c0de4310-0ed1-11e5-9d28-5efcc48f066b.png)

**Comment by HuanhuanSunMSFT** [comment]
This should be fixed in the latest build. Reopen this if not.

**Comment by ghost** [comment]
Repro in Dev14 RC + latest PoshTool and Dev14 RC + PoshTool from gallery. 
After you click "Get PowerShell Tools for Visual Studio" and choose download. It'll throw below error: This extension is already installed to all applicable products.

It seems I don't have permision to reopen issue. Please help to reopen it.

![untitled picture](https://cloud.githubusercontent.com/assets/12426589/8326834/7b98f9c8-1a96-11e5-9c14-4854f6aa055c.png)
