### ISSUE TITLE
"PowerShell" item template categories is missing when adding new item to C++ and few other projects

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#611]
This is TFS bug1185547 for Dev14 RTM.

Steps to reproduce:
1. Create a C++ Windows Store 8.1 Blank application project
2. Add new item
3. Check the new item template categories number in the "Add New Item" window

Expected:
New item template categories number: 11
VisualCpp
Xaml
Code
HLSL
Data
Resource
Web
Utility
PropertySheets
Graphics
PowerShell

Actual: 
The "PowerShell" item templates categories is missing.
New item template categories number: 10. 
VisualCpp
Xaml
Code
HLSL
Data
Resource
Web
Utility
PropertySheets
Graphics

PS: This issue also exists in the following projects:
a) Native project
b) Managed project
c) Phone 8.1 project
d) Windows Shared project
e) Windows Store UAP project
f) Android project

This should be fixed for July release.

**Comment by HuanhuanSunMSFT** [comment]
Fixed in PR #622
