### ISSUE TITLE
It still can be downloaded after installing Dev14Rel with PoshTool.

### ISSUE THREAD

**Issue by v-ldavid** [microsoft/poshtools#612]
Repro steps:
1. Install Dev14 latest Build with PoshTool.
2. launch VS, open Extensions and updates.

Expect:
It shows that PoshTool has been installed, and there is no PoshTool "Download" in "Online" list.

Actual: 
It shows that PoshTool has been installed, and click "Online", it still shows "Download" PoshTool. Restart VS, it still shows "Download" PoshTool.
![download poshtool](https://cloud.githubusercontent.com/assets/12929699/8200542/f3b47962-14f8-11e5-917b-eaa8b0169e7b.png)

**Comment by HuanhuanSunMSFT** [comment]
Close this as this is expected.
