### ISSUE TITLE
Intellisense is trying to do brace matching for the case it should not

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#614]
`
 ($vmInstance.ConfigurationSets[0].InputEndpoints | Where-Object {$_.Name -eq "SSH"} -ne $null)
`
`
(($vmInstance.ConfigurationSets[0].InputEndpoints | Where-Object {$_.Name -eq "SSH"}) -ne $null)
`

please note the difference(a pair of braces) between above two statements, first one is it used to be, second is the one I tried to get by modifying first statement. The way I modify is:
1. set cursor ahead of $vmInstance, add opening brace (it automatically complete the brace, remove the closing one as that is not where I want to close)
2. set cursor after "SSH}", add closing brace

Expected from step2: 
Closing brace was added

Actual:
The closing brace was ignored and only cursor position + 1

**Comment by HuanhuanSunMSFT** [comment]
Fixed in the PR #619
