### ISSUE TITLE
Download link point to download PoshTool dev14 in dev12

### ISSUE THREAD

**Issue by ghost** [microsoft/poshtools#624]
Repro step:
Make sure there is no PoshTool installed
1. Open .ps1 file with VS
2. There is a tip tell you that “Powershell Tools for Visual Studio are available”. Click "Install Now"

Expect:
Link point to download poshtool for dev12
Acutal:
Link point to download PoshTool for dev14. Details please see attachment.
![downloadposhtool](https://cloud.githubusercontent.com/assets/12426589/8429765/5f2f4c9e-1f5d-11e5-93b5-3d30dea6873d.png)

**Comment by HuanhuanSunMSFT** [comment]
There is a link on Dev14 page that points to Dev12
