### ISSUE TITLE
Posh Tools is unchecked by default when install Dev14 RTM and there is no reminder message

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#642]
Configurations: Dev14 RTM on Win Server 2012 R2

Repro Step:
1. Install Dev14 RTM
2. In the installation dialog, select custon installation.
3.In the next dialog, verify both Web Tools and Posh Tools were checked by default.

Expected: Both Web Tools and Posh Tools should be checked by default

Actual: Web Tools is checked bug Posh Tools is unchecked by default and there is no reminder message. Please see below screeshot:
![unchecked](https://cloud.githubusercontent.com/assets/12443209/8568167/f221c770-259d-11e5-9eb3-b822516c14a7.png)

**Comment by HuanhuanSunMSFT** [comment]
This is expected. We changed the default setup. The PowerShellTools is off by default and the web tools no longer has dependency on PowerShellTools.
