### ISSUE TITLE
[Debugging] Debugger doesn't stop at the breakpoint set after attaching to the running script

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#656]
Repro:
- Start running the script
- Attach to the running powershell process
- Wait for the debugger to stop at a code line and set a break point
- Continue 

Expected:
The debugger hit the break point

Actual:
See screenshot below
![debug_bug1](https://cloud.githubusercontent.com/assets/10081208/8814753/2c20fd2a-2fc5-11e5-966a-b5a594af29c9.jpg)

Here is the script:

```
#
# Script.ps1
#

Write-Host $Host.Runspace.Id

$count = 0
while($count -le 50)
{
    Write-Host $count
    $count = $count + 1
    sleep(2)
}

$username = Read-Host("What is your username?")
$password = Read-Host("What is your password?")
$monthName = Read-Host("Which month are you running this report for?")

Write-Host $username
Write-Host $password
Write-Host $monthName
```

**Comment by MrayerMSFT** [comment]
This is due to a regex bug in the regex we use to parse the callstack output. Exact cause has been found and will be fixed. Good catch @HuanhuanSunMSFT!
