### ISSUE TITLE
[Remote debugging] Try attaching while the remote machine is waiting for user input and then stop debugging will freeze VS

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#658]

**Comment by HuanhuanSunMSFT** [comment]
Another related issue: Try attaching while the remote machine is running a PS script in non-admin mode, then VS won't get attached to the process and cannot be stopped. Stopping debugging will freeze VS.

**Comment by MrayerMSFT** [comment]
For the user-input one, this is not our (aka: my :P) fault. It seems that whenever the script is waiting for user-input or is asleep (and maybe some other situations), it does not have the PowerShell engine loaded/it unloads it. Very odd choice of behavior, but I'll go ahead and see if the PowerShell team can shed any light on it. Will leave issue open for related note though.

<img width="960" alt="bug" src="https://cloud.githubusercontent.com/assets/12631548/8843649/10fddddc-30c0-11e5-8c15-94c2fcd13fc3.PNG">

**Comment by MrayerMSFT** [comment]
Talked to PowerShell team and can confirm that this is expected behavior.
