### ISSUE TITLE
[Remote debugging]Remote attach while user already in an existing remote session

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#662]
Repro step: 
Try to do remote attaching while user is already in an remote session.

There are two problems on below screenshot
1. Error message is inaccurate as I do have v5 installed
2. Imagine if I don't have v5 installed, would "retry" be helpful?
![capture](https://cloud.githubusercontent.com/assets/10081101/8832039/491aa11a-305b-11e5-91b8-861322c474af.PNG)

**Comment by MrayerMSFT** [comment]
Confused by what you mean by "already in a remote session". Do you mean already attached to a remote process, or in a remote session via the button by the REPL window? (for now I am assuming it is the second)

As for the error message, that shouldn't be appearing if you are doing remote attach...being in a remote session may be having some weird effect. Will investigate.
