### ISSUE TITLE
[Remote debugging] Consider to change transport name into "PowerShell Remote Debugging"

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#663]
![capture](https://cloud.githubusercontent.com/assets/10081101/8832173/3b481882-305c-11e5-94a1-7ef0f1f5e22f.PNG)

**Comment by MrayerMSFT** [comment]
I think specifying the tools part is important since it is our extension, aka, PowerShell Tools, which is providing that transport. I think if we had just PowerShell that could imply something officially related to PowerShell.

**Comment by MrayerMSFT** [comment]
Closing and not changing name.
