### ISSUE TITLE
[Remote Debugging]Remote attach to process of "localhost"

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#664]
Less likely this would happen in real life, but if someone does try to do that, he can not get any thing from it and plus, stopping the malfunctioning debugging hangs VS.

Repro:
1. Remote attaching, give computer name "localhost" (VS need elevated permission to do that)
2. Attach to a powershell process running on localhost
3. Observe the malfunctioning debugging state
4. Stop debugging

VS hangs.

**Comment by MrayerMSFT** [comment]
@EricMSFT, did you start the PowerShell as an administrator? Because that seems to be only way for me to repo this issue. Assuming that you didn't, then this is related to #658.

**Comment by MrayerMSFT** [comment]
Cause of issue identified as the PowerShell in step 2 not being started as admin. This is known issue with PowerShell v5 preview. Closing issue.
