### ISSUE TITLE
Local attach to process does not open the source in VS

### ISSUE THREAD

**Issue by ericdevg** [microsoft/poshtools#665]
Runs into this problem for a few times, now it seems to be consistently repro on my machine, even after restart VS, I'd hold my machine as it is till you got some chance to do some debugging on it. @MrayerMSFT

**Comment by MrayerMSFT** [comment]
Per in person convo, cause for this issue has been identified as a problem with the PowerShell window being debugged. This error appears to also be handled in changes in remote-dbg-tests.
