### ISSUE TITLE
There is a problem in the PowerShell host service error after deploying with an Azure Resource Group project on Windows 7

### ISSUE THREAD

**Issue by duyleMSFT** [microsoft/poshtools#667]
On Windows 7 x64:
- Install Visual Studio 2015
- Install Web Platform Installer (Web PI) from https://www.microsoft.com/web/downloads/platform.aspx
- Using Web PI, install Microsoft Azure SDK for .NET (VS 2015) - 2.7
- Using Web PI, install Microsoft Azure PowerShell
- Install PowerShell Tools for Visual Studio 2015 from https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597
1.  Open Visual Studio 2015
2.  Create a new C# Cloud/Azure Resource Group project, using the Web app template
3.  Open the WebSite.param.dev.json file under the Templates folder
4.  Change the siteName from null to "MyWebSite", hostingPlanName from null to "Dev" and siteLocation from null to "West US"
5.  Right-click the AzureResourceGroup node, choose Deploy -> New Deployment...
6.  In the Deploy to Resource Group dialog, sign in with an account that has an associated Microsoft Azure subscription, if not already
7.  Select a subscription
8.  Use the Resource Group dropdown to create a new one
9.  Click Deploy

Result:
An error occurs saying, "There is a problem in the PowerShell host service."

**Comment by HuanhuanSunMSFT** [comment]
After upgrading WMF from 3.0 to 4.0, this issue is resolved. Reopen the issue if there is still a problem @duyleMSFT
