### ISSUE TITLE
Cannot deploy, using an Azure Resource Group project, more than once in a VS session on Windows 7

### ISSUE THREAD

**Issue by duyleMSFT** [microsoft/poshtools#668]
On Windows 7 x64:
- Install Visual Studio 2015
- Install Web Platform Installer (Web PI) from https://www.microsoft.com/web/downloads/platform.aspx 
- Using Web PI, install Microsoft Azure SDK for .NET (VS 2015) - 2.7
- Using Web PI, install Microsoft Azure PowerShell
- Install PowerShell Tools for Visual Studio 2015 from https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597
1. Open Visual Studio 2015
2. Create a new C# Cloud/Azure Resource Group project, using the Web app template
3. Open the WebSite.param.dev.json file under the Templates folder
4. Change the siteName from null to "MyWebSite", hostingPlanName from null to "Dev" and siteLocation from null to "West US"
5. Right-click the AzureResourceGroup node, choose Deploy -> New Deployment...
6. In the Deploy to Resource Group dialog, sign in with an account that has an associated Microsoft Azure subscription, if not already
7. Select a subscription
8. Use the Resource Group dropdown to create a new one
9. Click Deploy
10. Repeat steps 3-9, but use different string values for the siteName and hostingPlanName parameters

Result:
The deployment fails with the following error:

[ERROR] At line:1 char:1767
- $UI = 'VS-';(Select-AzureProfile -Profile (New-AzureProfile -SubscriptionId '620 ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Executable script code found in signature block.

[ERROR] + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
[ERROR] + FullyQualifiedErrorId : TokenAfterEndOfValidScriptText

**Comment by HuanhuanSunMSFT** [comment]
This is a known issue in PowerShell 3.0. [Here](https://github.com/dahlbyk/posh-git/issues/134) is a workaround. And this also repros when you deploy using PowerShell console. So close this as it's not a PowerShell Tools issue.
