### ISSUE TITLE
[Local Debugging] VS can actually attach to PowerShell ISE

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#673]
In Attaching window, PowerShell ISE is excluded as a attachable type for debugging.

**Comment by MrayerMSFT** [comment]
Will be switching to using Get-PSHostProcess info as our attachable process filter. This correctly lists PowerShell ISE, our host, and hopefully all other attachable processes. This should also be a motivation to complete task #649.

**Comment by MrayerMSFT** [comment]
Expected behavior now on remotedbg-filter-change branch. Will be creating PR with this and a few other things soon(TM).

![process](https://cloud.githubusercontent.com/assets/12631548/8947003/a376b380-354a-11e5-8ac8-3b8ee6bc1566.PNG)
