### ISSUE TITLE
[Remote Debugging] Error dialog pops while trying to attach to a remote process

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#674]
The error dialog:

**Comment by HuanhuanSunMSFT** [comment]
Some remote machine information: 
OS: Win 8.1
Host version: 5.0.10105.0

Local machine:
OS: Win 10
Host version: 5.0.10192.0
VS 2015 RTM

**Comment by MrayerMSFT** [comment]
As per our in person conversation, you didn't start the PowerShell on Windows 8.1 as admin. So this is expected behavior.
