### ISSUE TITLE
Unexpected Microsoft.PythonTools.Attacher.exe in the running processes 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#691]
MS build 3.0.1487
VS 2015 RTW build
1. In VS2015, create a powershell script project. You can use the one pasted below.  (the problem is not script specific)
2. Set a breakpoint somewhere in the script. 
3. F5 to stop at the breakpoint
4. Select "Debug->Attach to Process" in the Attach to Process dialog. Leave all settings with default values. Then chose "PowerShell host service" to attach to. Close the dialog
5. Set the focus back in the editor then hit F10 and F5. 
6. Click on stop debugging in the toolbar
7. Repeat steps 3 and 4.

Notice, in the Attach To Process, you will see an extra process named "Microsoft.PythonTools.Attacher.exe", which probably was launched by the PoshTools on the second attach. 

I understand this isn't a typical "Local Attach" scenario, but there was nothing preventing me from doing so. 

Script attached:
# 
# Script.ps1
# 

Get-Service
Get-Process

$var = 'hello'
$number = 1
$numbers = 1,2,3,4,5,6,7,8,9

$debug = "`$computer contains $computer"
$head = "Column`tColumn`tColumn"                            

$filter1 = "name='BITS'"
$computer = 'BITS'
$filter2 = "name=$computer'"
$var = 'hello'
$var | Get-Member
$svc = Get-Service
$svc[0].name
$name = $svc[1].name
$name.Length
$name.ToUpper()

$service = 'bits'
$name = "Service is $service.ToUpper()"
$upper = $name.ToUpper()
$name = "Service is $upper"
Write-Host $name

$name = (Get-Service)[0].name
Write-Host $name

**Comment by jinglouMSFT** [comment]
BTW, this machine does have Python Tools for Visual Studio installed.

**Comment by MrayerMSFT** [comment]
Ok well that makes way more sense now. From looking at the PTVS code, it appears they launch their attacher to detect if a process is attachable. So, when you selected debug all types, the PTVS attacher must have been launched to see if PTVS could attach to it. On a related note, I am going to say that we will not allow attaching to the host process for now/until it is specifically asked for.
