### ISSUE TITLE
In Debug interactive window, no intellisense for command parameters. 

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#7]
E.g., I define a Cmdlet Get-Proc with a mandatory parameter ComputerName, after typing Get-Proc and dash, I cannot see parameter ComputerName showing in the auto completion list.

**Comment by ASayre** [comment]
Related to adamdriscoll/poshtools#162

**Comment by HuanhuanSunMSFT** [comment]
Fixed together with  adamdriscoll/poshtools#162
