### ISSUE TITLE
Cannot drag the scrollbar of Format Preview part on Command Explorer

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#704]
Config: 
Dev14 Ent RTM + Latest PowerShell Tool(https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev) on Win Server 2012 R2

Repro Steps:
1. Launch VS and open the Command Explorer.
2. Double click one Command and open that.
3. Input all the informations for Parameters and check the checkbox of 'Format as Hashtable'.
4. On the Format Preview, drag the scrollbar.

Expected: we can drag the scrollbar successfully.
Actual: we cannot drag the scrollbar. see below screenshot.

More Info:
We can scroll the textbox by scrolling the mouse.

![cannotdrag](https://cloud.githubusercontent.com/assets/12443209/9930477/83eaf4b0-5d66-11e5-87e8-c9cdedbb3604.png)

**Comment by adamdriscoll** [comment]
@erwindevreugd - Small one but figured you should be aware. Issues might be popping up in this repo as well as mine!

**Comment by erwindevreugd** [comment]
@adamdriscoll thanks for the headsup! Found a couple so far, mostly relatively minor cosmetic issues, I'll follow up on them.

**Comment by ASayre** [comment]
Fixed in https://github.com/adamdriscoll/poshtools/pull/341 @erwindevreugd Thanks for Fixing this up!
