### ISSUE TITLE
There's a vertical line in the checkbox of Online in Parameters part in Command Explorer

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#705]
Config: 
Dev14 Ent RTM + Latest PowerShell Tool(https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev) on Win Server 2012 R2

Repro Steps:
1. Launch VS and open the Command Explorer
2. Search the command 'Use-WindowsUnattend', double click the Command and open that
3. Open the dropdown list and select online
4. In Parameters part, check if  the checkbox of Online display well

Expected: the checkbox of Online display well
Actual: there's a vertical line in the checkbox of Online

![onlinemode](https://cloud.githubusercontent.com/assets/12443209/9930685/12ed0148-5d68-11e5-8f53-a71708b1224d.JPG)

**Comment by ASayre** [comment]
Fixed in https://github.com/adamdriscoll/poshtools/pull/341 @erwindevreugd Thanks for Fixing this up!
