### ISSUE TITLE
The tooltips of parametereditor are the same with the parameter name which not very clear

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#706]
Config: 
 Dev14 Ent RTM + Latest PowerShell Tool(https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev) on Win Server 2012 R2

Repro Steps:
1. Launch VS and open the Command Explorer
2. Double click one Command and open that.
3. Verify the tooltips of the parametereditor

Actual: the tooltips are the same with the parameter name.
Expected: the tooltips should be more meaningful for user to understand the sense of the parameter.
![tooltips](https://cloud.githubusercontent.com/assets/12443209/9931058/c13b831c-5d6a-11e5-9d6d-3e5778c24c2d.JPG)

**Comment by erwindevreugd** [comment]
The tooltips are filled with a help message that is provided by the PowerShell module of the command, if no message is set it falls back to the parameter name. However, the Azure module is one of the few modules I've found that actually sets this field. Unfortunately the help message field is the only field that holds anything meaningful to use here.

**Comment by HuanhuanSunMSFT** [comment]
Thanks @erwindevreugd for the detailed explanation. I'll close this issue since this is something expected and up to module owners. @jinglou- @AndreSayreMSFT @adamdriscoll
