### ISSUE TITLE
Opening up the REPL Window has DocumentSite error

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#84]
Config: Dev12 Update 4
Tried to open up REPL Window from the Quick-Launch window

![image](https://cloud.githubusercontent.com/assets/10080679/6069707/6b1f7bd0-ad3b-11e4-92ec-00c5258473a0.png)

**Comment by ASayre** [comment]
After trying to open it again, the following entry is added to the activity log:

  <entry>
    <record>1207</record>
    <time>2015/02/05 21:33:28.740</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Repl.PromptMargin..ctor(IWpfTextViewHost wpfTextViewHost, IEditorFormatMap editorFormatMap)&#x000D;&#x000A;   at Microsoft.VisualStudio.Repl.PromptMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin parent)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__2(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>

**Comment by huguesv** [comment]
I'm getting that activity log error too (but not that dialog).  Dev12 Update 4 too.

**Comment by ASayre** [comment]
For me, only when PTVS is installed
