### ISSUE TITLE
Object reference not set to an instance of an object when lauching VS 2013 after intalling PoshTools

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#85]
Configuration:
VS 2013 Update 4
PoshTools: https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts
NTVS 30129.00

Repro:
1. Start VS after installation

Result:
Spawning the 64-bit process failed with object reference not set to an instance of an object.
See screenshot

![capture](https://cloud.githubusercontent.com/assets/10081483/6069656/165898d4-ad3b-11e4-84c2-2672190340c9.PNG)

**Comment by ASayre** [comment]
This is what shows on first launch of VS after installing our tools.
