### ISSUE TITLE
Ctrl+Space can trigger the auto completion

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#9]

**Comment by ASayre** [comment]
Merged pull request as it doesn't cause any regressions, but not closing the original issue as there still remains stuff to be done.

•Does this need to trigger in the REPL Window w/regards to completion? PTVS's Repl has Ctrl-space working for example. [However, the Completion Command isn't sent for PS's repl window when that happens. Is PTVS doing something funny?]

•This doesn't automatically select the first item. Eg, can't "Ctrl-Space; Enter" like in ISE and other VS languages

•Deletion of text doesn't re-filter when Ctrl-Space originally triggers the Intellisense

**Comment by RogerBestMsft** [comment]
Added functionality to automatically select the first item when "Ctrl-space".
