### ISSUE TITLE
The REPL window uses options from Tools|Options|Text Editor 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#95]
VS 2013.4
PoshTools: https://ci.appveyor.com/api/buildjobs/v253c204g0hbxcmm/artifacts/Binaries/Release12.0/PowerShellTools.vsix

Repro:
1. Start VS
2. Create a powershell script project (you probably don't need to do this)
3. From View->Other Windows->Powershell Debug Interactive to launch the REPL windows
4. Notice that command prompted is highlighted.  See the attached pix.
5. You have to de-select Tools->options->Text editor->highlight current line to get rid of the hightlight

Expect:
The REPL window doesn't have highlight on the current line.

![capture](https://cloud.githubusercontent.com/assets/10081483/6070239/c9e9dcb0-ad3f-11e4-8eb1-9fd3116f79ee.PNG)

**Comment by ASayre** [comment]
Related to #111 ?  Investigate these

**Comment by ASayre** [comment]
Related to #207 ?

**Comment by ASayre** [comment]
[Closing as dupe]
